### ISSUE TITLE
Unstable zonal flows for kinetic electron runs when zed_upwind > 0

### ISSUE THREAD

**Issue by DenSto** [stellaGK/stella#59]
I've found that large-scale zonal flows are numerically unstable when using kinetic electrons and the implicit linear solve. (There's actually residual growth in the adiabatic case too, but it's sufficiently small that you really need to look for it).  This is what I know so far:
- zed_upwind has to be finite. If things are centered, there is no instability. The growth rate of the instability also depends on zed_upwind
- increasing the number of zed-grid points (decreasing delzed) reduces the growth rate
- There is no instability in the explicit case
- this doesn't appear to happen in gs2
- This is a large scale instability. For small electron scale zonal flows, there is no instability. The growth rate converges to some value as kx -> 0, so I suspect some stabilization from the Bessel functions.
- If I remove the spatial dependency for Maxwell_mu by using bmag at the outboard midplane in vpamu_grids.f90, this problem goes away.

The last point seems to suggest that it's a problem with how we're centering the maxwellian, but I can't seem to find the source of the bug! Note that there is no problem if gradpar varies in space, which is even more confusing, since gradpar and maxwell_mu are handled the same way.  

There could be a typo in response_matrix.fpp where the centering is handled, but I can't seem to find it. Perhaps I need another set of eyes.

Attached is a zip file containing a minimal input file, which contains only parallel streaming, nothing else.

[test_case.zip](https://github.com/stellaGK/stella/files/8631311/test_case.zip)

**Comment by ZedThree** [comment]
Is this something that used to work and now is unstable? One possibility is that the scheme itself has the instability. Moving from centred differences to upwinding with the same number of points can introduce errors/dissipation, although that usually means the convergence is slower in the number of points, rather than introducing an instability.

I've had a quick look through, the only suspicious thing I saw was that in `parallel_streaming::sweep_g_zed` there is a small one-sided piece: https://github.com/stellaGK/stella/blob/7a3fb2f4677bda08907d83ee467a9694d1a65ceb/parallel_streaming.f90#L925-L926

That doesn't appear in other places with similar terms, e.g. [`response_matrix::sweep_zed_zonal_response`](https://github.com/stellaGK/stella/blob/7a3fb2f4677bda08907d83ee467a9694d1a65ceb/response_matrix.fpp#L793), or [`response_matrix::get_dgdphi_matrix_column`](https://github.com/stellaGK/stella/blob/7a3fb2f4677bda08907d83ee467a9694d1a65ceb/response_matrix.fpp#L483), which has explicit handling for the boundaries.

I have absolutely no idea if it's wrong, but that's the only thing that stood out to me.

**Comment by DenSto** [comment]
I'll have to check that line out, but the issue I'm seeing is for periodic modes, and so that part of the code shouldn't be used.

I also can't seem to find a commit where this case isn't unstable. I may have to look deeper into the numerical scheme for this one.

**Comment by DenSto** [comment]
For the time being, I've gone with the hacky solution and just centered `maxwell_mu` precisely at the midpoint. This seems to get rid of the numerical instability, and hopefully won't alter the numerical accuracy of the scheme.  I'm not quite sure why I don't need to exactly center `gradpar`, but I'm going to think about this more later...
