### ISSUE TITLE
Restarted simulations fail on initialisation when new input file contains more lines than original input file  (netCDF error)

### ISSUE THREAD

**Issue by rd1042** [stellaGK/stella#85]
To reproduce:
 - Run a simulation with save_for_restart = .true. (example attached, but delete the ".txt" suffix)
 -  Modify the input input file to ginit_option = "many"
 - Add an additional line to the input file e.g. add delt_option = "check restart" in the "knobs" namelist, or add a line of comment anywhere in the input file
-  Run the simulation. 

When I do this, I get the error message:
ERROR: NetCDF: Start+count exceeds dimension bound in variable "input_file" in varid:       54 variable name: input_file writing variable
ERROR STOP Aborted by neasyf_error

My guess is that:
 - Running a simulation from resart, stella uses the same .out.nc file as the initial simulation, so it can just append new data on to the end
 - The old .out.nc file is opened, and save_input is called to save the contents new input file in the old .out.nc file
 - Somehow, stella (or neasyf) determines the dimensions of this data based on the old input file, rather than the new.

@ZedThree - possibly a neasyf issue, or an issue which manifests badly when using neasyf?

[example.in.txt](https://github.com/stellaGK/stella/files/9288132/example.in.txt)

**Comment by ZedThree** [comment]
Ah, sorry, this is neasy-f hard aborting when it detects an error. Previously this would have just printed a warning and carried on.

I can see three possible fixes:

1. make `neasyf_error` take an optional argument to only print the error message and carry on, as before. This will mean that restarting with a larger input file will cut off the "extra" lines
2. make `nlines` an unlimited dimension so that larger input files can be written.
3. rework how inputs are saved in the netCDF file so as to preserve the history of inputs across restarts. There's at least a couple of ways of achieving that -- an extra "run" dimension, or separate groups for each restart, `run001`, `run002` etc

I think 3 would be the best thing going forward, but it would be a fair bit more work and has implications for existing analysis and post-processing tools, so would need to be done carefully.

The second option is probably the best immediate fix. The only catch is that we'd need to "blank" the existing value on restarts, in case the input was shorter.

@DenSto thoughts?

**Comment by DenSto** [comment]
I would agree that 2 or 1 are probably the easiest options.  I'm happy with either.
