### ISSUE TITLE
Inconsistencies for high ky in linear runs

### ISSUE THREAD

**Issue by SStroteich** [stellaGK/stella#88]
In linear runs, the solution of stella differs from the GENE solution for high kys as can be seen in the picture below. These modes do not seem to converge. The corresponding files can be found at [https://www.pavlosipp.com/stella](https://www.pavlosipp.com/stella)

![freq_comp](https://user-images.githubusercontent.com/17315788/184657973-61cc5187-c148-47bf-a56e-e4849f720f79.jpg)

**Comment by HanneThienpondt** [comment]
I've run your input file, and it seems like simply increasing the number of time steps solves the issue. In this picture below you can see I plotted the unstable modes from your input file. I increased the normalized time and then you clearly find convergence. 
![unstable](https://user-images.githubusercontent.com/76125875/186424673-565b9105-06b0-4b9a-98d6-fc1dc9cd19aa.png)

Be careful to not plot a gamma output from stella which corresponds to stable modes, this is why you obtain this strange peak at ky=10, these values are just wrong. 
![stable](https://user-images.githubusercontent.com/76125875/186424667-f6ba5c31-eebf-446f-824a-1e12f9a1ee12.png)

Looking at the evolution of the potential squared it is clear when a mode is unstable (increasing phi^2) or when it is stable (decreasing phi^2). 
![potential](https://user-images.githubusercontent.com/76125875/186424657-1b0daed2-4014-40bf-bfaa-2f49f72ee7c1.png)

**Comment by HanneThienpondt** [comment]
I've looked into your issue and I can't find any problems with stella at high ky. Here's the spectrum I've obtained based on your input files. The units on the plot are those used in stella.
![spectra](https://user-images.githubusercontent.com/76125875/186617177-bb41b205-dc99-41ff-85d8-aec1182e8b0e.png)

If I zoom in on the high-ky modes which are unstable then it is clear that the lower the growth rate, the longer the time trace needs to be in order to reach convergence. Thus in order to match the GENE results, you simply need to prolong the simulations. 
![unstable](https://user-images.githubusercontent.com/76125875/186617354-0a172979-f0e1-458e-b691-736fa15d3201.png)

The strange values you obtain at high-ky is because you are plotting gamma(ky) for modes that are stable, for which gamma as calculated by stella has no real meaning, since there is no exponential growth. This is usually clear from the time evolution of the growth rate, you should never plot a gamma(ky) if gamma has not converged yet, and for a stable mode it will never converge. It helps to add the standard mean deviation of the time evolution to your gamma(ky) plot so that you immediately know whether your spectrum is converged. 
![stable](https://user-images.githubusercontent.com/76125875/186617759-0f316ff8-4ab2-4823-9f62-937fec5dd960.png)

Whether a mode is stable or unstable is clear from the time evolution of the potential squared, for unstable modes the potential grows exponentially while for a stable mode the potential decreases. The modes you've plotted which have high growth rates at high-ky are stable modes and should have gamma=nan in your plot.
![potential](https://user-images.githubusercontent.com/76125875/186617937-8804f57c-9a2e-42e8-91b8-1cb1f1024504.png)

**Comment by DenSto** [comment]
This looks resolved to me! For any newcomers looking at this issue, note that GENE and stella's timestep differ by sqrt(2).
